import type { TeaProfile } from "./types";

export const PRESET_TEAS: TeaProfile[] = [
  // ─── Green ───
  {
    id: "longjing",
    name: "Longjing",
    chineseName: "龙井",
    category: "green",
    liquorColor: "#c8d96b",
    icon: "leaf",
    tempC: 80,
    ratioGramsPer100ml: 3,
    steepsSec: [15, 20, 30, 45, 60, 90],
    autoAdvance: true,
    description: "Dragon Well — pan-fired, chestnutty, flat jade leaves.",
  },
  {
    id: "biluochun",
    name: "Bi Luo Chun",
    chineseName: "碧螺春",
    category: "green",
    liquorColor: "#bcd25e",
    icon: "twist",
    tempC: 80,
    ratioGramsPer100ml: 3,
    steepsSec: [12, 18, 25, 40, 60, 85],
    autoAdvance: true,
    description: "Green Snail Spring — downy spirals, fruity and floral.",
  },
  {
    id: "maofeng",
    name: "Huangshan Maofeng",
    chineseName: "黄山毛峰",
    category: "green",
    liquorColor: "#d3dc7e",
    icon: "bud",
    tempC: 80,
    ratioGramsPer100ml: 3,
    steepsSec: [15, 20, 30, 45, 70, 100],
    autoAdvance: true,
    description: "Yellow Mountain Fur Peak — orchid aroma, sweet finish.",
  },
  {
    id: "anjibaicha",
    name: "Anji Bai Cha",
    chineseName: "安吉白茶",
    category: "green",
    liquorColor: "#dde4a4",
    icon: "needle",
    tempC: 80,
    ratioGramsPer100ml: 3,
    steepsSec: [15, 20, 30, 45, 65],
    autoAdvance: true,
    description: "A green tea despite the name — pale, umami, spring grass.",
  },

  // ─── Yellow ───
  {
    id: "junshan",
    name: "Junshan Yinzhen",
    chineseName: "君山银针",
    category: "yellow",
    liquorColor: "#e3d370",
    icon: "needle",
    tempC: 80,
    ratioGramsPer100ml: 3,
    steepsSec: [20, 30, 45, 60, 90],
    autoAdvance: true,
    description: "Rare yellow tea — mellow, sweet corn, smooth.",
  },

  // ─── White ───
  {
    id: "silverneedle",
    name: "Silver Needle",
    chineseName: "白毫银针",
    category: "white",
    liquorColor: "#ecdc9a",
    icon: "needle",
    tempC: 85,
    ratioGramsPer100ml: 3.5,
    steepsSec: [20, 30, 45, 60, 90, 120, 150],
    autoAdvance: true,
    description: "Downy buds only — delicate, melon, honeysuckle.",
  },
  {
    id: "baimudan",
    name: "White Peony",
    chineseName: "白牡丹",
    category: "white",
    liquorColor: "#e8d284",
    icon: "bud",
    tempC: 85,
    ratioGramsPer100ml: 3.5,
    steepsSec: [15, 25, 40, 55, 80, 110, 140],
    autoAdvance: true,
    description: "Bai Mudan — buds and leaves, fuller and fruitier.",
  },
  {
    id: "shoumei",
    name: "Shou Mei",
    chineseName: "寿眉",
    category: "white",
    liquorColor: "#dbb45f",
    icon: "leaf",
    tempC: 90,
    ratioGramsPer100ml: 4,
    steepsSec: [15, 25, 40, 60, 90, 120, 160],
    autoAdvance: true,
    description: "Rustic aged-friendly white — dates, hay, honey.",
  },

  // ─── Light Oolong ───
  {
    id: "tieguanyin",
    name: "Tieguanyin",
    chineseName: "铁观音",
    category: "oolong-light",
    liquorColor: "#cfd66a",
    icon: "pearl",
    tempC: 95,
    ratioGramsPer100ml: 5.5,
    steepsSec: [15, 20, 25, 35, 45, 60, 90, 120],
    autoAdvance: true,
    description: "Iron Goddess — rolled jade pearls, lilac and cream.",
  },
  {
    id: "gaoshan",
    name: "Gaoshan",
    chineseName: "高山茶",
    category: "oolong-light",
    liquorColor: "#d8dd7d",
    icon: "pearl",
    tempC: 95,
    ratioGramsPer100ml: 5.5,
    steepsSec: [15, 20, 25, 35, 50, 70, 100, 130],
    autoAdvance: true,
    description: "Taiwan high mountain — alpine air, butter, gardenia.",
  },
  {
    id: "baozhong",
    name: "Baozhong",
    chineseName: "包种",
    category: "oolong-light",
    liquorColor: "#d4d874",
    icon: "twist",
    tempC: 90,
    ratioGramsPer100ml: 5,
    steepsSec: [20, 25, 35, 45, 60, 90, 120],
    autoAdvance: true,
    description: "Barely-oxidized strips — lilac, fresh and green.",
  },

  // ─── Dark Oolong ───
  {
    id: "dahongpao",
    name: "Da Hong Pao",
    chineseName: "大红袍",
    category: "oolong-dark",
    liquorColor: "#c07a2e",
    icon: "strip",
    tempC: 99,
    ratioGramsPer100ml: 6,
    steepsSec: [10, 15, 20, 30, 45, 60, 90, 120],
    autoAdvance: true,
    description: "Big Red Robe — Wuyi rock oolong, roast and minerals.",
  },
  {
    id: "rougui",
    name: "Rou Gui",
    chineseName: "肉桂",
    category: "oolong-dark",
    liquorColor: "#b96f28",
    icon: "strip",
    tempC: 99,
    ratioGramsPer100ml: 6,
    steepsSec: [10, 15, 20, 30, 45, 60, 90, 120],
    autoAdvance: true,
    description: "Cassia rock oolong — cinnamon spice, stone fruit.",
  },
  {
    id: "shuixian",
    name: "Shui Xian",
    chineseName: "水仙",
    category: "oolong-dark",
    liquorColor: "#c4832f",
    icon: "strip",
    tempC: 99,
    ratioGramsPer100ml: 6,
    steepsSec: [10, 15, 22, 32, 45, 65, 90, 120],
    autoAdvance: true,
    description: "Narcissus — old-bush depth, orchid and wet stone.",
  },
  {
    id: "dancong",
    name: "Fenghuang Dancong",
    chineseName: "凤凰单丛",
    category: "oolong-dark",
    liquorColor: "#d1912f",
    icon: "twist",
    tempC: 95,
    ratioGramsPer100ml: 6,
    steepsSec: [8, 12, 18, 25, 35, 50, 70, 95, 120],
    autoAdvance: true,
    description: "Phoenix single-bush — honey orchid, famously aromatic.",
  },
  {
    id: "dongding",
    name: "Dong Ding",
    chineseName: "冻顶",
    category: "oolong-dark",
    liquorColor: "#c98f3a",
    icon: "pearl",
    tempC: 95,
    ratioGramsPer100ml: 5.5,
    steepsSec: [15, 20, 28, 38, 55, 75, 105],
    autoAdvance: true,
    description: "Classic roasted Taiwan ball oolong — toasty, sweet.",
  },

  // ─── Black / Red ───
  {
    id: "jinjunmei",
    name: "Jin Jun Mei",
    chineseName: "金骏眉",
    category: "black",
    liquorColor: "#c1651f",
    icon: "bud",
    tempC: 90,
    ratioGramsPer100ml: 4.5,
    steepsSec: [10, 15, 20, 30, 45, 60, 90],
    autoAdvance: true,
    description: "Golden Beautiful Eyebrow — bud-only, honey and cocoa.",
  },
  {
    id: "keemun",
    name: "Keemun",
    chineseName: "祁门红茶",
    category: "black",
    liquorColor: "#a94e1c",
    icon: "strip",
    tempC: 95,
    ratioGramsPer100ml: 4.5,
    steepsSec: [10, 15, 22, 32, 45, 65, 90],
    autoAdvance: true,
    description: "Qimen hongcha — winey, orchid, gentle smoke.",
  },
  {
    id: "dianhong",
    name: "Dianhong",
    chineseName: "滇红",
    category: "black",
    liquorColor: "#b85a1b",
    icon: "bud",
    tempC: 92,
    ratioGramsPer100ml: 4.5,
    steepsSec: [10, 15, 20, 30, 45, 65, 90],
    autoAdvance: true,
    description: "Yunnan red — golden tips, malt, sweet potato.",
  },
  {
    id: "lapsang",
    name: "Lapsang Souchong",
    chineseName: "正山小种",
    category: "black",
    liquorColor: "#9e4a1e",
    icon: "strip",
    tempC: 95,
    ratioGramsPer100ml: 4.5,
    steepsSec: [10, 15, 22, 32, 48, 70, 95],
    autoAdvance: true,
    description: "Pinewood-dried original black tea — longan, campfire.",
  },

  // ─── Pu-erh ───
  {
    id: "shengpuer-young",
    name: "Young Sheng Pu-erh",
    chineseName: "生普洱（新）",
    category: "puer-sheng",
    liquorColor: "#d6b545",
    icon: "cake",
    tempC: 95,
    ratioGramsPer100ml: 5,
    steepsSec: [10, 12, 15, 20, 30, 45, 60, 90, 120, 180],
    autoAdvance: true,
    description: "Raw and lively — bitter-sweet, apricot, huigan.",
  },
  {
    id: "shengpuer-aged",
    name: "Aged Sheng Pu-erh",
    chineseName: "生普洱（老）",
    category: "puer-sheng",
    liquorColor: "#b97e2c",
    icon: "cake",
    tempC: 99,
    ratioGramsPer100ml: 5,
    steepsSec: [10, 15, 20, 30, 45, 60, 90, 120, 180, 240],
    autoAdvance: true,
    description: "Time-softened sheng — camphor, dried fruit, depth.",
  },
  {
    id: "shoupuer",
    name: "Shou Pu-erh",
    chineseName: "熟普洱",
    category: "puer-shou",
    liquorColor: "#6e3a1a",
    icon: "cake",
    tempC: 100,
    ratioGramsPer100ml: 5,
    steepsSec: [10, 12, 18, 25, 40, 60, 90, 120, 180],
    autoAdvance: true,
    description: "Ripe pu-erh — earthy, smooth, dark chocolate.",
  },

  // ─── Heicha ───
  {
    id: "liubao",
    name: "Liu Bao",
    chineseName: "六堡茶",
    category: "heicha",
    liquorColor: "#7c4620",
    icon: "brick",
    tempC: 100,
    ratioGramsPer100ml: 5,
    steepsSec: [10, 15, 20, 30, 45, 70, 100, 150],
    autoAdvance: true,
    description: "Guangxi dark tea — betel nut, cellar, mellow.",
  },

  // ─── Herbal ───
  {
    id: "chrysanthemum",
    name: "Chrysanthemum",
    chineseName: "菊花茶",
    category: "herbal",
    liquorColor: "#e9d780",
    icon: "flower",
    tempC: 95,
    ratioGramsPer100ml: 2,
    steepsSec: [30, 45, 60, 120, 180],
    autoAdvance: true,
    description: "Whole dried blossoms — cooling, honeyed, caffeine-free.",
  },
];

export function getPresetTea(id: string): TeaProfile | undefined {
  return PRESET_TEAS.find((t) => t.id === id);
}
